project:
  type: website
  render:
    - index.qmd
    - docs/
  preview:
    port: 7827
    browser: false
    navigate: false
    timeout: 3600

website:
  title: ArgMap
  description: "Advancing Policy Insights: Opinion Data Analysis and Debate Structuring Using LLMs"
  site-url: https://argmap.bhatia.dev/
  repo-url: https://github.com/aadityabhatia/polis-argmap/
  repo-actions: source
  page-navigation: true
  page-footer: "© 2024 Aaditya Bhatia"
  image: images/og.png
  favicon: images/logo.png
  open-graph: true
  navbar:
    logo: images/logo.png
    background: primary
    search: false
    right:
      - icon: github
        href: https://github.com/aadityabhatia/polis-argmap

format:
  html:
    toc: true
    toc-expand: 1
    code-fold: true
    smooth-scroll: true
    page-layout: full
    fig-align: center
    theme:
      light:
        - sandstone
        - mermaid.scss
      dark:
        - darkly
    mermaid:
      theme: neutral
    grid:
      body-width: 1800px

argdown:
  sourceHighlighter: web-component
  mode: web-component
  webComponent:
    withoutMaximize: true
  model:
    removeTagsFromText: true
