flowchart LR
    subgraph Metrics
        Accuracy
        Precision
        FalsePositiveRate
        UnsureRate
    end

    subgraph Tasks
        Classification ---> Accuracy & Precision & FalsePositiveRate & UnsureRate
        Classification[Classification: Spam Detection]
    end

    subgraph Variables
        TargetLabels[Target Labels]
        TargetLabels --> Classification
        %% TargetLabels --> ThreeClass[ACCEPT, UNSURE, REJECT]
        %% TargetLabels --> SevenClass[ACCEPT, UNSURE, \nSPAM, IRRELEVANT, \nUNPROFESSIONAL, SCOPE, COMPLEX]
        %% ThreeClass & SevenClass --> Classification
        ReasoningTechnique[Reasoning Technique] --> Classification
        Examples[Use of Examples] --> Classification
    end
