flowchart LR
    subgraph Metrics
        Accuracy:::selected
        Precision:::selected
        FalsePositiveRate:::selected
        UnsureRate:::selected
    end

    subgraph Tasks
        Classification --- Accuracy & Precision & FalsePositiveRate & UnsureRate
        Classification[Classification: Spam Detection]:::selected
    end

    subgraph Variables
        Prompt & LanguageModel[Language Model] --- Classification
        TargetLabels[Number of Target Labels]:::selected --- Classification
        Examples[Use of Examples]:::selected --- Classification
        ReasoningTechnique[Reasoning Technique]:::selected --- Classification
    end

    classDef selected fill:#8c8